import string

LETTERS_UPPERCASE = list(string.ascii_uppercase)
LETTERS_LOWERCASE = list(string.ascii_lowercase)
LETTERS_AMOUNT = len(LETTERS_UPPERCASE)

LETTERS_TRANSITION_ALLOWABLE_ERROR = 0.05
GRAMMAR_ALLOWABLE_ERROR = 0.02

FULLNESS_TRAININGS_AMOUNT = 20
